### ISSUE TITLE
Install howto?

### ISSUE THREAD

**Issue by SuselK** [eugeneglova/binance-trading-bot#10]
Hello Eugene,
i found yout reposity.
 
Have yo a install tutorial?
 
Best Regards
Susan

**Comment by eugeneglova** [comment]
Hey Susan,

just install it from
https://github.com/eugeneglova/binance-trading-bot/releases/tag/v1.1.9
at the bottom you have exe or dmg links
I started writing russian tutorial
https://github.com/eugeneglova/binance-trading-bot/wiki/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F-%D0%BD%D0%B0-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%BC-%D1%8F%D0%B7%D1%8B%D0%BA%D0%B5

Thanks,
Eugene

**Comment by SuselK** [comment]
Good Morning Eugen...
sorry, it is not possible to install the bot on linux (Debian).
There are many mistakes ...

Do you have a tutorial for the installation under linux?
am I installing this wrong?

Please help :-)

Best Regards
Susan

- Download and install as root.
- Running with different user (not as root)

------------------------------------------------------------------------
Mistakes on install:
------------------------------------------------------------------------
Command: npm install

Messages:
....
> electron@10.1.3 postinstall /home/root/eugeneglova/binance-trading-bot-1.1.11/node_modules/electron
> node install.js

npm WARN lifecycle binance-trading-bot@1.1.8~postinstall: cannot run in wd binance-trading-bot@1.1.8 electron-builder install-app-deps (wd=/home/root/eugeneglova/binance-trading-bot-1.1.11)
npm WARN binance-trading-bot@1.1.8 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
....


------------------------------------------------------------------------
Mistakes on starting the bot:
------------------------------------------------------------------------
I start the bot not under the user: root
Command: npm run electron-dev

Messages:
...

> binance-trading-bot@1.1.8 electron-dev /home/root/eugeneglova/binance-trading-bot-1.1.11
> concurrently "PORT=3009 BROWSER=none npm run start" "wait-on http://localhost:3009 && electron ."

[0]
[0] > binance-trading-bot@1.1.8 start /home/root/eugeneglova/binance-trading-bot-1.1.11
[0] > rescripts start
[0]
[0] ℹ ｢wds｣: Project is running at http://0.0.0.0:3009/
[0] ℹ ｢wds｣: webpack output is served from
[0] ℹ ｢wds｣: Content not from webpack is served from /home/root/eugeneglova/binance-trading-bot-1.1.11/public
[0] ℹ ｢wds｣: 404s will fallback to /
[0] Starting the development server...
[0]
[0] Compiled successfully!
[0]
[0] You can now view binance-trading-bot in the browser.
[0]
[0]   http://localhost:3009
[0]
[0] Note that the development build is not optimized.
[0] To create a production build, use npm run build.
[0]
[1] Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[1] /home/root/eugeneglova/binance-trading-bot-1.1.11/node_modules/electron/dist/electron exited with signal SIGSEGV
[1] wait-on http://localhost:3009 && electron . exited with code 1
^C[0] PORT=3009 BROWSER=none npm run start exited with code SIGINT
...

**Comment by eugeneglova** [comment]
I added built for linux 
https://github.com/eugeneglova/binance-trading-bot/releases/download/v1.1.11/BinanceTradingBot-1.1.11.AppImage

https://github.com/eugeneglova/binance-trading-bot/releases/tag/v1.1.11
