### ISSUE TITLE
Problems and Improvments

### ISSUE THREAD

**Issue by henesseye** [eugeneglova/binance-trading-bot#11]
I have tested the tool and found some problems
1. Order size adjustment after Taking Profit
The size and price of existing limit orders should be adjusted after Taking Profit. The orders will be left with the initial value.

2. A trade is open and I cancel the orders. And reset the range for limit orders and press restart. Then the bot automatically executes all orders as a market at the current price. So the position size is wrong and the entry failed.

3. Improvement
Amending the orders. It would be good if the placed orders can be adjusted during the open trade. For example I want to set additional limit orders via grid. Then they should be entered in the grid and set again. Maybe it makes sense to add a new button "Reset Orders" to do this.

4. Improvement
Reduce to Init value
It would be desirable to have the possibility to execute a reduction to the initial value of the order. Example:
Long Entry 18500, Size 0.1
Limit Orders 18200, 18000 with 0.1
Current position 0.3 with Average Entry 182333.33
A reduction will sell 0.2 at 182335 (+0.1% due to fees). This reduces the position to the init value of 0.1 at an entry price of 18233. This improves the initial position

**Comment by eugeneglova** [comment]
hi,
thank you for testing it

1. well it should adjust it but only if position size decreases so position
size equals or less than size of possible new grid
example limit order sizes;
0.1, 0.1, 0.4, 1, 1.5, 2.4 and 4.7

[1]   { price: 12.806, amount: 0.1, priceDiff: 0.193 },
[1]   { price: 12.614, amount: 0.1, priceDiff: 0.366 },
[1]   { price: 12.248, amount: 0.4, priceDiff: 0.429 },
[1]   { price: 11.819, amount: 1, priceDiff: 0.54 },
[1]   { price: 11.287, amount: 1.5, priceDiff: 0.66 },
[1]   { price: 10.633, amount: 2.4, priceDiff: 0.75 },
[1]   { price: 9.888, amount: 4.7, priceDiff: 0.7 }

so when position size is 0.1 + 0.1 + 0.4 = 0.8 and take profit was for
example 0.4 position size became 0.4 and it should not update limit orders
as next is still 1
but if take profit 0.6 so pos size 0.2 it should update limit orders to
start from 0.4
make sense ?


btw I made a fix today 1.1.10 there was a bug it can't calculate price and
submit all new grid orders with market price :(

2. oh shit, seems this is exactly what I've fixed

3. it seems it should work already, so cancel all orders with button or in
binance app and restart should create new orders, but it works based on
first order or position size


Thanks,
Eugene

**Comment by eugeneglova** [comment]
@henesseye 

> 4. Improvement
> Reduce to Init value
> It would be desirable to have the possibility to execute a reduction to the initial value of the order. Example:
> Long Entry 18500, Size 0.1
> Limit Orders 18200, 18000 with 0.1
> Current position 0.3 with Average Entry 182333.33
> A reduction will sell 0.2 at 182335 (+0.1% due to fees). This reduces the position to the init value of 0.1 at an entry price of 18233. This improves the initial position
> 

what about additional 2 input fields for take profit orders section like
where to place first TP order [0.1%] 
size of reduce position [70%] (if 0 no order will be set and it will be use regular TP grid)

so it could be set for different position sizes based on number of limit orders 
in your example it will be 
tp grid:
[0.3] [1] [5] [0] [0]
[0.25] [1] [5] [0] [0]
[0.15] [1] [5] [0.1] [67]

so when position size will be 0.3 (0.1 + 0.1 + 0.1) it will set first take profit order 0.1% with 67% of pos (0.201) and other 33% will be used 0.15 - 1% regular TP grid so it will use 5 orders TP grid and 1 for reduction 

or if you have other vision on this feature please let me know
because I don't think it's  required for small size positions

**Comment by henesseye** [comment]
> @henesseye
> 
> > 1. Improvement
> >    Reduce to Init value
> >    It would be desirable to have the possibility to execute a reduction to the initial value of the order. Example:
> >    Long Entry 18500, Size 0.1
> >    Limit Orders 18200, 18000 with 0.1
> >    Current position 0.3 with Average Entry 182333.33
> >    A reduction will sell 0.2 at 182335 (+0.1% due to fees). This reduces the position to the init value of 0.1 at an entry price of 18233. This improves the initial position
> 
> what about additional 2 input fields for take profit orders section like
> where to place first TP order [0.1%]
> size of reduce position [70%] (if 0 no order will be set and it will be use regular TP grid)
> 
> so it could be set for different position sizes based on number of limit orders
> in your example it will be
> tp grid:
> [0.3] [1] [5] [0] [0]
> [0.25] [1] [5] [0] [0]
> [0.15] [1] [5] [0.1] [67]
> 
> so when position size will be 0.3 (0.1 + 0.1 + 0.1) it will set first take profit order 0.1% with 67% of pos (0.201) and other 33% will be used 0.15 - 1% regular TP grid so it will use 5 orders TP grid and 1 for reduction
> 
> or if you have other vision on this feature please let me know
> because I don't think it's required for small size positions

hi, thanks for your reply

I just installed the fix and the reset of the orders are now working. no more market buys/sells. great!
That should work for reducing the position as you mentioned.
but i would try to set the reduce flag on the limit orders entry grid and not on the TP grid. let's say, i set 4 Limit Orders on the entry grid. For example, as soon as order nr. 4 is triggered, it would set a TP Limit order nearly the entry price and reduce the position size to the entered value. i usually set it manually to the entry value or DCA Level 1. 
<img width="669" alt="image" src="https://user-images.githubusercontent.com/55426104/101629525-c944e780-3a21-11eb-95b7-3a70dc7b04bc.png">

**Comment by eugeneglova** [comment]
ok, I will try to make it in price grid so you know better where it will be triggered
I see you use almost classic martingale 1 2 2 2 2 2

**Comment by henesseye** [comment]
> ok, I will try to make it in price grid so you know better where it will be triggered
> I see you use almost classic martingale 1 2 2 2 2 2

yeah, with more dca levels, i use dynamic dca.
i try to calculate the new position size so that the new average price is e.g. 0.3% away from the current price. Therefore the position size for the next DCA order has to be adjusted dynamically as well.
But your tool runs really smooth without any delays. nice one

**Comment by eugeneglova** [comment]
btw before bot I created a tool to build orders and calculate profit for DCA
https://eugeneglova.github.io/dca/
however a lot of data which I understand only :-))))

**Comment by eugeneglova** [comment]
it will be something like this
so you can use DCA level or percentage and provide where to place TP order for it using percentage or points
![image](https://user-images.githubusercontent.com/2828226/101731822-45e0d000-3acd-11eb-8dd9-f6713b84cbae.png)

**Comment by henesseye** [comment]
> it will be something like this
> so you can use DCA level or percentage and provide where to place TP order for it using percentage or points
> ![image](https://user-images.githubusercontent.com/2828226/101731822-45e0d000-3acd-11eb-8dd9-f6713b84cbae.png)

that looks very good. i'm curious to try out the feature. do i understand it correctly. the third column "reduce at", stands for the distance to the entry price? So at 0.1% a Limit-Sell order is placed above the Entry if I want to reduce the Long-Trade to DCA1 level for example

**Comment by eugeneglova** [comment]
@henesseye yes, `reduce at` will be the distance where you want to place your take profit order with amount of `reduce to`
so if [0.1%] and [1] and position size is 4 for example and your entry amount is 1 it will add new limit sell order with size 3 and usual take profit order for size 1 (rest of position) at distance from take profit settings. I will add tooltips
![image](https://user-images.githubusercontent.com/2828226/101788431-2370a600-3b11-11eb-85c5-146105843774.png)

**Comment by eugeneglova** [comment]
https://github.com/eugeneglova/binance-trading-bot/releases/tag/v1.1.11
done

**Comment by henesseye** [comment]
Hi Eugen
Thank you very much for your work. Looks good.
Something caught my eye.
After a Reduce, the existing DCA orders would have to be adjusted. Because by the Reduce to e.g. DCA level 1 the DCA orders would have to be recalculated and set again from this position size. Otherwise the old orders will remain with the wrong position size.  Therefore the DCAing must start again from the new level. Here is an example

<img width="682" alt="image" src="https://user-images.githubusercontent.com/55426104/101878114-548fbb80-3b8f-11eb-9106-8d44a6510fd2.png">

**Comment by eugeneglova** [comment]
so based on your screen I think it will work like this
entry pos size 0.003 
1. dca order 0.003: pos size 0.006
2. dca order 0.003: pos size 0.009
3. dca order 0.003: pos size 0.012
4. dca order 0.006: pos size 0.018 and it sets tp order to 0.05% with value of 0.018-0.003=0.015 and rest 0.003 will be second tp order

once order 0.015 filled so position size updated to 0.003 bot will adjust dca limit orders to add 0.003 at 0.08% distance etc
doesn't it work like this for you? I think it should, I will double check as my bot running for many pairs and I started using this feature too

**Comment by henesseye** [comment]
Yes, that's exactly how it should work. with a reduce, the calculation of the dca levels starts again from this level. But this is unfortunately not the case.
Currently, however, the old orders remain, so in this case those (No. 5 / 6) with the value 3x / 2x.
I had to intervene manually. Would be good if you could check this again. otherwise really good work man

**Comment by eugeneglova** [comment]
you can always cancel orders and restart pair, but I will double check

**Comment by eugeneglova** [comment]
I run ADA long with this settings, I had position size 23 and first TP was 15 and other 8 was 2 2 2 and 2 and next limit order was 24 and 47, after I got TP filled I see it adjusted the grid so now next order is 15 and distance 2.64%

![image](https://user-images.githubusercontent.com/2828226/101918574-8ed27a80-3bda-11eb-81a6-b88d7ed8657e.png)
![image](https://user-images.githubusercontent.com/2828226/101918775-d0632580-3bda-11eb-9a18-fbaacd22bcc4.png)
![image](https://user-images.githubusercontent.com/2828226/101918957-1324fd80-3bdb-11eb-85ad-ae3ab7a68f70.png)
