### ISSUE TITLE
How can i change ip?

### ISSUE THREAD

**Issue by SuselK** [eugeneglova/binance-trading-bot#12]
Hello,
i installed on linux server.
I start the bot with: "npm start"

	You can now view binance-trading-bot in the browser.
	  http://localhost:3000

I must change the Ip-address für the bot. Where i can change the IP and the Port?

Best Regards
Susan

**Comment by SuselK** [comment]
Hello...
ok the bot is running with the normal server-ip.

But i have a blank page.
What is wrong?
Best Regards
Susan


Here the full source-code...

`

body
--
  | <div id="root"></div>
  | 
  | This HTML file is a template.
  | If you open it directly in the browser, you will see an empty page.
  |  
  | You can add webfonts, meta tags, or analytics to this file.
  | The build step will place the bundled scripts into the <body> tag.
  |  
  | To begin the development, run `npm start` or `yarn start`.
  | To create a production bundle, use `npm run build` or `yarn build`.
  | 
  | <script src="/static/js/bundle.js"></script><script src="/static/js/0.chunk.js"></script><script src="/static/js/main.chunk.js"> 
  | </script>

body



`

**Comment by eugeneglova** [comment]
@MeoncoSusan do not `run npm start` it's only runs web control panel for bot, use `npm run electron-dev` 
but actually it's better to download built and run it.
