### ISSUE TITLE
Preserve Filter Settings

### ISSUE THREAD

**Issue by henesseye** [eugeneglova/binance-trading-bot#13]
I hope it does not annoy you when I open issues here :-)

It would be helpful if the filter settings are saved each time I change the tab.
It would also be helpful if I could adjust the sorting of the trading pairs manually. The newly created ones are always at the bottom.

**Comment by eugeneglova** [comment]
settings persistence - done, will be included in new version

for sorting, as I use `index` of pair for bot it's danger to remove pair from the list :-) I had plans to add id instead but didn't add it still.
But I will think about it visually I can sort it and even persist but in config it will be still sorted by date added.

**Comment by eugeneglova** [comment]
preserve filter settings https://github.com/eugeneglova/binance-trading-bot/releases/tag/v1.1.11

**Comment by eugeneglova** [comment]
sorting https://github.com/eugeneglova/binance-trading-bot/releases/tag/v1.2.0
