### ISSUE TITLE
Leverage settings

### ISSUE THREAD

**Issue by doftorul** [eugeneglova/binance-trading-bot#14]
Hi Eugen, great work !

- Does the bot sets its own leverage ?
- After the grid is set for several coins, including TP and SL grids, do you need to manually take actions to TP or SL ?
- How many coins in parallel max are recommended ?
- Does the bot saves its status in a DB ? Can it be re-initialized to "factory default" ?

Many thanks for your answers

**Comment by eugeneglova** [comment]
> Does the bot sets its own leverage ?

it doesn't work with leverage, so if you have 100х you can't have long grid :)

> After the grid is set for several coins, including TP and SL grids, do you need to manually take actions to TP or SL ?

no, if you set all it should work automatically, now SL created after position open and for the size of position, when position  averaged SL order will be updated

> How many coins in parallel max are recommended ?

actually there is no limitation, it has some warning for event emitter for 10 listeners, but I ran more than 10 and it's ok

> Does the bot saves its status in a DB ? Can it be re-initialized to "factory default" ?

Bot saves all in `config.json` (not in bot folder, but in OS app data), but there are some presets like `default` for tp grid and some presets for price grid.

If you want to restore it to defaults your need find `config.json` and remove it, but I think it's better to create your own configuration for pairs to understand how it works.
Check https://github.com/eugeneglova/binance-trading-bot/wiki there is russian instructions with path to files

**Comment by doftorul** [comment]
Many thanks for your answers.

Asked about the leverage as i started the bot for a test run and saw binance's default x20 leverage, felt i need to ask.
Are you guys running it with Cross 1X ?

**Comment by eugeneglova** [comment]
cross 20х :) and even 40х but better 20х
