### ISSUE TITLE
Running multiple instances

### ISSUE THREAD

**Issue by doftorul** [eugeneglova/binance-trading-bot#15]
Hi Eugen and many thanks for your keen and fast help !

If i were to run 2 instances for 2 different accounts, other than running it from source, how can i install a 2nd instance on the same machine ?

**Comment by eugeneglova** [comment]
good question :-) I will add support for this

**Comment by doftorul** [comment]
Electron is not very versatile for multi-instance of the same installed program with separate folders for the actual program and where the data is stored.

**Comment by doftorul** [comment]
If you would commit the latest source that is in the binary, i can run multiple instances from source

**Comment by eugeneglova** [comment]
the reason it doesn't work as both uses one config file so if you save api keys in one instance it will modify it for other, as config file stored in one place per program name in system folders. I use `electron-store` npm package for configuration, so I will add configurable `cwd` or `name` for config path or filename not sure how to allow to modify it for now, but I will find out :)
https://github.com/sindresorhus/electron-store#cwd

**Comment by doftorul** [comment]
I remember i did something similar a while back with a Quasar/Vue app packaged with electron and in that one i just allowed the selection of which config/params file the user should use.

Maybe in the API keys tab you can add a button to select the config file ?

**Comment by eugeneglova** [comment]
the problem I need to know that info before loading config. I thought to add command line argument like --cwd=app2 but it's not good UX for GUI users

**Comment by eugeneglova** [comment]
I added partial multi account support, partial because telegram command will use only default account
https://gumroad.com/l/WWLFh 1.2.7
you should be able to get updated version by this link
