### ISSUE TITLE
The Option: Auto start ?

### ISSUE THREAD

**Issue by SuselK** [eugeneglova/binance-trading-bot#17]
Hello,
i found the option "Auto start".

What is it?
The bot trades automatically if this is activated?

Best Regards
Susan

![what_is_auto_start](https://user-images.githubusercontent.com/54170080/101897268-95e19480-3baa-11eb-9aa8-a3ec3152c7ef.png)

**Comment by eugeneglova** [comment]
it will start automatically if you close the App and open again.

**Comment by SuselK** [comment]
Ah ok.
Thank you :-).
