### ISSUE TITLE
Reduce Function

### ISSUE THREAD

**Issue by henesseye** [eugeneglova/binance-trading-bot#19]
I've got still an issue with the reduce function
shouldn't the position here be reset to DCA level 2? Currently it looks as if the complete position is closed here. 
Position size 0.074
Limit order 0.074

<img width="2278" alt="image" src="https://user-images.githubusercontent.com/55426104/102225149-255ab080-3ee7-11eb-9222-aec46231fe84.png">

**Comment by eugeneglova** [comment]
@henesseye just found the issue with `reduce to` it's used default grid x amount 1 2 2 2  instead of your settings, I am planning to release update on sunday

**Comment by eugeneglova** [comment]
@henesseye should be fixed in 1.1.2, also I added show current DCA Level when expand position on trading tab
