### ISSUE TITLE
Запуск бота

### ISSUE THREAD

**Issue by m-e-n3** [eugeneglova/binance-trading-bot#21]
Привет Евгений!
У меня Mac iOS, вообще не понимаю как запустить бота на Макбуке
скачал файлы(жаль скрин не приложить)
В общем прошу помощи как его запустить?
Заранее спасибо за ответ!

**Comment by eugeneglova** [comment]
https://gumroad.com/l/WWLFh
тут есть версия под макОС готовая 
на гитхабе старая версия кода

**Comment by m-e-n3** [comment]
Да, спасибо
Я видел эту страницу, но пока не решился на покупку
Скажите, есть ли пробный период Евгений?
На скрине у Вас показан хороший рост депозита для этого ведь определенные настройки нужны?

**Comment by m-e-n3** [comment]
еще вопрос:
есть ли свежая статистика?

**Comment by eugeneglova** [comment]
настройки подскажу с чего начать
могу попробовать сделать пробный
![image](https://user-images.githubusercontent.com/2828226/106129640-7e1d9a00-6171-11eb-97e1-8a9f65374e50.png)

**Comment by m-e-n3** [comment]
Был бы очень признателен и благодарен
моя почта
m-e-n3@yandex.ru
понять хоть что это и с чем его есть)))

**Comment by m-e-n3** [comment]
Спасибо, поддержку получил!
