### ISSUE TITLE
installation support

### ISSUE THREAD

**Issue by janfleming144** [eugeneglova/binance-trading-bot#23]
Hi, how can i get complied windows version to run and test?

**Comment by didikrm** [comment]
I had the same question.

**Comment by janfleming144** [comment]
@eugeneglova can you help?

**Comment by eugeneglova** [comment]
@janfleming144 @didikrm source code now outdated as I sell the bot but it could be still compiled, so use next commands
clone repository and then inside it run this

```
npm i
npm run electron-pack
```
and it should be compiled to `dist` folder

P.S. make sure node js installed

**Comment by janfleming144** [comment]
how to contact you to discuss sell of the bot?

**Comment by janfleming144** [comment]
@eugeneglova please help

**Comment by eugeneglova** [comment]
@janfleming144 you should see my email in profile

**Comment by janfleming144** [comment]
i have received all the support i needed. thanks
